def T9(entrada):
    entrada.replace('a', 2)
    entrada.replace('b', 2)
    entrada.replace('c', 2)
    entrada.replace('d', 3)
    entrada.replace('e', 3)
    entrada.replace('f', 3)
    entrada.replace('g', 4)
    entrada.replace('h', 4)
    entrada.replace('i', 4)
    entrada.replace('j', 5)
    entrada.replace('k', 5)
    entrada.replace('l', 5)
    entrada.replace('m', 6)
    entrada.replace('n', 6)
    entrada.replace('o', 6)
    entrada.replace('p', 7)
    entrada.replace('q', 7)
    entrada.replace('r', 7)
    entrada.replace('s', 7)
    entrada.replace('t', 8)
    entrada.replace('u', 8)
    entrada.replace('v', 8)
    entrada.replace('w', 9)
    entrada.replace('x', 9)
    entrada.replace('y', 9)
    entrada.replace('z', 9)
    return entrada


x = int(input('Frases a serem alteradas: '))
for i in range(x):
    entrada = input('Frase a ser alterada: ')
    print(f'{i+1}°-> {T9(entrada)}')
