def T9(frase_T9):
    global i
    frase_T9 = frase_T9.replace('a', '2')
    frase_T9 = frase_T9.replace('á', '2')
    frase_T9 = frase_T9.replace('à', '2')
    frase_T9 = frase_T9.replace('ã', '2')
    frase_T9 = frase_T9.replace('â', '2')
    frase_T9 = frase_T9.replace('b', '2')
    frase_T9 = frase_T9.replace('c', '2')
    frase_T9 = frase_T9.replace('ç', '2')
    frase_T9 = frase_T9.replace('d', '3')
    frase_T9 = frase_T9.replace('e', '3')
    frase_T9 = frase_T9.replace('ê', '3')
    frase_T9 = frase_T9.replace('é', '3')
    frase_T9 = frase_T9.replace('è', '3')
    frase_T9 = frase_T9.replace('f', '3')
    frase_T9 = frase_T9.replace('g', '4')
    frase_T9 = frase_T9.replace('h', '4')
    frase_T9 = frase_T9.replace('i', '4')
    frase_T9 = frase_T9.replace('í', '4')
    frase_T9 = frase_T9.replace('î', '4')
    frase_T9 = frase_T9.replace('ì', '4')
    frase_T9 = frase_T9.replace('j', '5')
    frase_T9 = frase_T9.replace('k', '5')
    frase_T9 = frase_T9.replace('l', '5')
    frase_T9 = frase_T9.replace('m', '6')
    frase_T9 = frase_T9.replace('n', '6')
    frase_T9 = frase_T9.replace('o', '6')
    frase_T9 = frase_T9.replace('ó', '6')
    frase_T9 = frase_T9.replace('ò', '6')
    frase_T9 = frase_T9.replace('ô', '6')
    frase_T9 = frase_T9.replace('õ', '6')
    frase_T9 = frase_T9.replace('p', '7')
    frase_T9 = frase_T9.replace('q', '7')
    frase_T9 = frase_T9.replace('r', '7')
    frase_T9 = frase_T9.replace('s', '7')
    frase_T9 = frase_T9.replace('t', '8')
    frase_T9 = frase_T9.replace('u', '8')
    frase_T9 = frase_T9.replace('u', '8')
    frase_T9 = frase_T9.replace('ú', '8')
    frase_T9 = frase_T9.replace('û', '8')
    frase_T9 = frase_T9.replace('ù', '8')
    frase_T9 = frase_T9.replace('v', '8')
    frase_T9 = frase_T9.replace('w', '9')
    frase_T9 = frase_T9.replace('x', '9')
    frase_T9 = frase_T9.replace('y', '9')
    frase_T9 = frase_T9.replace('z', '9')
    print(f'{i + 1}°-> {frase_T9}')


x = int(input('Frases a serem alteradas: '))
for i in range(x):
    entrada = input('Frase a ser alterada: ').lower()
    T9(entrada)
